#adding variables in playbook using vars
- name: adding variables
  hosts: localhost
  vars:
    wish: "Hello"
    me: "Manoj"
    nick: "Manu"
  tasks:
  - name: print variables here
    ansible.builtin.debug:
      msg: "{{wish}} everyone. My name is {{me}}. You can call me {{nick}}"