# simple install using loop
- name: loops for simple install
  hosts: localhost
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present 
    loop:
    - git
    - mysql
    - postfix